### ISSUE TITLE
"Unauthenticated source" for js script

### ISSUE THREAD

**Issue by rrbutani** [Murad-Bummos/GenreExplorer#1]
One of the js libraries (bootstrap) is still loaded over http which causes issues when your site is loaded over https. [here, for example](https://github.com/Murad-Bummos/GenreExplorer/blob/master/authorization_code/public/index.html#L19)

Your code currently tries to load: `http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js` 
which is good (using the basically canonical cdn for bootstrap), except that you hard coded http. 

Instead you should use a protocol relative URL (which you already use elsewhere): `//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js`

Alternatively, if you're comfortable abandoning support for very old/obscure browsers, you can hardcode for https.

**Comment by Murad-Awad** [comment]
We actually fixed this issue cause we did the same thing with jquery yesterday on the live website. Since we are using heroku it has a separate repo. I will upload the bootstrap.min.js file now, although our solution already works.

**Comment by rrbutani** [comment]
The issue a) currently isn't fixed (error still appears in Chrome for me) and b) isn't appropriately fixed by self-hosting js libraries (See issue #2)

The appropriate solution is to either use protocol relative links or hard code for https.

**Comment by Murad-Awad** [comment]
It is fixed now.
