### ISSUE TITLE
Self-hosting js libraries

### ISSUE THREAD

**Issue by rrbutani** [Murad-Bummos/GenreExplorer#2]
You currently use a self-hosted jquery library (which you switched to to try to fix the unauthenticated script error).

Whether or not to self-host js libraries such as jquery is widely debated but for a website like yours (heroku hosting, small user base, not many scripts) using a cdn for jquery (such as Google's) makes a lot more sense (less bandwidth for your server meaning better speeds for users, less bandwidth use / better speed for users because of caching, etc.)

If you don't want to switch to a CDN for js libraries, at the very least use a minified version of the jquery library (the version you have currently weighs in at 280+ KB, over 3x the size of the minified library).

**Comment by Murad-Awad** [comment]
Fixed this. I might switch back to cdn later but the server is handling it fine and I'm too lazy to change it back.
